server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /springboot-provider
spring:
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: dubbo-providert
    qos-accept-foreign-ip: false
    qos-enable: false
  scan:
    basePackages: com.nacos.impl
  provider:
    owner: mr.softrock
  protocol:
    name: dubbo
    port: 20880
    payload: 20971528
  consumer:
    timeout: 500000
    lazy: true
    check: false

  registry:K
    address: nacos://120.92.78.198:8848
    parameters[namespace]: 8e6155c7-1149-4d45-a5f4-c87c2bbb4e47
  metadata-report:
   address: nacos://120.92.78.198:8848
